repo_config:
  main: "deb http://deb.debian.org/debian bookworm main contrib non-free"
  updates: "deb http://deb.debian.org/debian bookworm-updates main contrib non-free"
  security: "deb http://security.debian.org/debian-security bookworm-security main contrib non-free"
