---
- name: Instalace běžných uživatelských balíčků
  apt:
    name:
      - firefox
      - thunderbird
      - libreoffice
      - vlc
      - gimp
      - deluge
    state: present
  when: ansible_os_family == 'Debian'

- name: Nastavení Postfixu
  include_tasks: postfix.yml
  when: "'mail' in group_names"

- name: Nastavení UFW firewallu
  include_tasks: ufw.yml
