---
# Nastavení UFW firewallu
- name: Instalace UFW
  apt:
    name: ufw
    state: present

- name: Povolení UFW
  community.general.ufw:
    state: enabled

- name: Povolení SSH
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Nastavení výchozích politik
  community.general.ufw:
    policy: "{{ item.policy }}"
    direction: "{{ item.direction }}"
  loop:
    - { policy: allow, direction: in }
    - { policy: allow, direction: out }
