---
# Konfigurace pro Linux Mint stanice

- name: Instalace běžných uživatelských balíčků
  apt:
    name:
      - firefox
      - thunderbird
      - libreoffice
      - vlc
      - gimp
      - transmission
    state: present
    
- name: Nastavení Postfix pro odesílání emailů jako satelit
  include_tasks: postfix.yml
  
- name: Nastavení UFW firewallu
  include_tasks: ufw.yml
