---
# Základní konfigurace pro všechny systémy

- name: Nastavit Ubuntu codename pro Linux Mint
  set_fact:
    mint_ubuntu_codename: "{{ mint_ubuntu_mapping[ansible_distribution_release | lower] }}"
  when: ansible_distribution == 'LinuxMint'

- name: Nastavit české repozitáře
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  notify: update_cache  # Název musí přesně odpovídat handleru

- name: Aktualizovat cache balíčků
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Nastavit locale
  include_tasks: locale.yml

- name: Nastavit timezone
  copy:
    content: "Europe/Prague\n"
    dest: /etc/timezone
  become: yes
  notify: aktualizovat timezone

- name: Instalovat základní balíčky
  apt:
    name:
      - sudo
      - vim
      - curl
      - wget
      - htop
      - ntp
      - logrotate
      - fail2ban
    state: present
  become: yes

- name: Install Czech language packs for Mint
  apt:
    name:
      - language-pack-cs-base
      - language-pack-gnome-cs
    state: present
  when: 
    - ansible_distribution == 'LinuxMint'

- name: Nastavit Ubuntu codename pro Linux Mint
  set_fact:
    mint_ubuntu_codename: "{{ mint_ubuntu_mapping[ansible_distribution_release | lower] }}"
  when: ansible_distribution == 'LinuxMint'

- name: Nastavit české repozitáře
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
  notify: update_cache
