---
# roles/base/tasks/main.yml
# Optimalizovaná základní konfigurace

- name: Nastavit proměnné pro Linux Mint
  block:
    - name: Zjistit kódové jméno Ubuntu
      set_fact:
        mint_ubuntu_codename: "{{ mint_ubuntu_mapping[ansible_distribution_release | lower] }}"
    
    - name: Přidat Mint repozitáře
      apt_repository:
        repo: "deb http://packages.linuxmint.com {{ mint_repo_codename }} main upstream import backport"
        state: present
  when: ansible_distribution == 'LinuxMint'

- name: Aktualizovat cache balíčků
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags: packages

- name: Nastavit lokalizaci
  include_tasks: locale.yml
  tags: localization

- name: Nastavit časovou zónu
  timezone:
    name: Europe/Prague
  become: yes
  tags: time

- name: Instalovat základní balíčky
  apt:
    name:
      - sudo
      - vim
      - curl
      - wget
      - htop
      - mc
      - logrotate
      - fail2ban
    state: present
    update_cache: no  # Cache již aktualizováno dříve
  become: yes
  tags: packages

- name: Instalovat české jazykové balíčky pro Mint
  apt:
    name:
      - language-pack-cs-base
      - language-pack-gnome-cs
    state: present
  when: 
    - ansible_distribution == 'LinuxMint'
    - ansible_distribution_release in ['victoria', 'vera']  # Pouze pro podporované verze
  tags: [packages, localization]

# Kontrola faktů
- name: Zobrazit detekovanou distribuci
  debug:
    msg: "Distribuce: {{ ansible_distribution }}, Verze: {{ ansible_distribution_release }}"
