# roles/repo_manager/tasks/main.yml
---
- name: Záloha původního sources.list
  copy:
    src: "/etc/apt/sources.list"
    dest: "/etc/apt/sources.list.bak_{{ ansible_date_time.iso8601 }}"
    remote_src: yes
  become: yes

- name: Vytvořit nový sources.list
  template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list
    mode: '0644'
  become: yes
  notify: update_cache

- name: Přidat GPG klíče
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ repo_gpg_keys }}"
  become: yes
  when: repo_gpg_keys is defined

- meta: flush_handlers
