# roles/repo_manager/tasks/main.yml
---
- name: Záloha původního official-package-repositories.list
  copy:
    src: "/etc/apt/sources.list.d/official-package-repositories.list"
    dest: "/etc/apt/sources.list.d/official-package-repositories.list.bak_{{ ansible_date_time.iso8601 }}"
    remote_src: yes
  become: yes

- name: Přidat podporu pro HTTPS
  apt:
    name: ca-certificates
    state: present
    update_cache: yes

- name: Vytvořit nový official-package-repositories.list
  template:
    src: templates/sources.list.j2
    dest: /etc/apt/sources.list.d/official-package-repositories.list
    mode: '0644'
  become: yes
  notify: update_cache

- name: Přidat GPG klíče
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ repo_gpg_keys }}"
  become: yes
  when: repo_gpg_keys is defined

- meta: flush_handlers



